---
title: "Phylogenetic Comparative Analysis Package and Vignette"
output: rmarkdown::html_vignette
date: 04/26/2022
vignette: >
  %\VignetteIndexEntry{Phylogenetic Comparative Analysis Package and Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
*Collaborators: Savvy Cornett & Jyhreh Johnson*

## Background
<<<<<<< HEAD
Phylogenetic Comparative Analysis or Phylogenetic Comparative Methods (PCMs) are a set of statistical methods that are used by biologist, geneticist, and anthropologists to analyze phylogenetic trees and track/presents species traits (Pennell & Harmon, 2013). 

## Introduction
In this package, we have included a dataset for the Sonic Hedgehog vertebrate orthologs (SHH_orthologs.csv) from the NIH database. We also have two functions: one for making a phylogenetic tree, and the other for doing a phylogenetic scatterplot. 
=======
Phylogenetic Comparative Analysis or Phylogentic Comparative Methods (PCMs) are a set of statistical methods that are used by biologist, geneticist, and anthropologists to analyze phylogenetic trees and track/presents species traits (Pennell & Harmon, 2013). The purpose of this method is to utilize the phylogenetic trees to address the evolutionary hypotheses and diversification of species.
>>>>>>> b356b027a65757c1420d961e1cba131bdc02ffe3

## Introduction
Within this package, we have included a data set of 

<<<<<<< HEAD
## References 
Pennell, M. W., & Harmon, L. J. (2013). An integrative view of phylogenetic comparative methods: Connections to population genetics, community ecology, and paleobiology: Integrative comparative methods. Annals of the New York Academy of Sciences, 1289(1), 90–105. <https://doi.org/10.1111/nyas.12157>
=======




## References
Pennell, M. W., & Harmon, L. J. (2013). An integrative view of phylogenetic comparative methods: Connections to population genetics, community ecology, and paleobiology: Integrative comparative methods. Annals of the New York Academy of Sciences, 1289(1), 90–105. https://doi.org/10.1111/nyas.12157
>>>>>>> b356b027a65757c1420d961e1cba131bdc02ffe3
